services:
  - type: web
    name: glf-stat-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  - type: web
    name: glf-stat-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://glf-stat-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
